2025-06-14 15:14:58,608 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:14:58,615 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:14:58,621 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:15:03,681 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:15:03,685 - livekit.agents - INFO - starting worker
2025-06-14 15:15:03,687 - livekit.agents - INFO - starting inference executor
2025-06-14 15:15:03,746 - livekit.agents - INFO - initializing process
2025-06-14 15:15:08,807 - livekit.agents - DEBUG - initializing inference runner
2025-06-14 15:15:08,807 - livekit.agents - DEBUG - initializing inference runner
2025-06-14 15:15:11,052 - pydot - DEBUG - pydot initializing
2025-06-14 15:15:11,052 - pydot - DEBUG - pydot 3.0.4
2025-06-14 15:15:11,052 - pydot - DEBUG - pydot initializing
2025-06-14 15:15:11,052 - pydot - DEBUG - pydot 3.0.4
2025-06-14 15:15:11,118 - pydot.dot_parser - DEBUG - pydot dot_parser module initializing
2025-06-14 15:15:11,118 - pydot.dot_parser - DEBUG - pydot dot_parser module initializing
2025-06-14 15:15:11,122 - pydot.core - DEBUG - pydot core module initializing
2025-06-14 15:15:11,122 - pydot.core - DEBUG - pydot core module initializing
2025-06-14 15:15:33,766 - livekit.agents - INFO - killing process
2025-06-14 15:15:33,767 - livekit.agents - ERROR - worker failed
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\channel.py", line 47, in arecv_message
    return _read_message(await dplx.recv_bytes(), messages)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 35, in recv_bytes
    len_bytes = await self._reader.readexactly(4)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 750, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 543, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\cli\_run.py", line 88, in _worker_run
    await worker.run()
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\worker.py", line 409, in run
    await self._inference_executor.initialize()
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\supervised_proc.py", line 168, in initialize
    init_res = await asyncio.wait_for(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2025-06-14 15:15:33,777 - livekit.agents - ERROR - Error in _read_ipc_task
Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 35, in recv_bytes
    len_bytes = await self._reader.readexactly(4)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 748, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\utils\log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\cli\watcher.py", line 120, in _read_ipc_task
    msg = await channel.arecv_message(self._pch, proto.IPC_MESSAGES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\channel.py", line 47, in arecv_message
    return _read_message(await dplx.recv_bytes(), messages)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 43, in recv_bytes
    raise DuplexClosed() from e
livekit.agents.utils.aio.duplex_unix.DuplexClosed
2025-06-14 15:16:32,622 - watchfiles.main - WARNING - process already dead, exit code: 0
2025-06-14 15:16:38,033 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:16:38,038 - livekit.agents - INFO - starting worker
2025-06-14 15:16:38,039 - livekit.agents - INFO - starting inference executor
2025-06-14 15:16:38,094 - livekit.agents - INFO - initializing process
2025-06-14 15:16:42,403 - livekit.agents - DEBUG - initializing inference runner
2025-06-14 15:16:42,403 - livekit.agents - DEBUG - initializing inference runner
2025-06-14 15:16:44,533 - pydot - DEBUG - pydot initializing
2025-06-14 15:16:44,533 - pydot - DEBUG - pydot 3.0.4
2025-06-14 15:16:44,533 - pydot - DEBUG - pydot initializing
2025-06-14 15:16:44,533 - pydot - DEBUG - pydot 3.0.4
2025-06-14 15:16:44,582 - pydot.dot_parser - DEBUG - pydot dot_parser module initializing
2025-06-14 15:16:44,582 - pydot.dot_parser - DEBUG - pydot dot_parser module initializing
2025-06-14 15:16:44,586 - pydot.core - DEBUG - pydot core module initializing
2025-06-14 15:16:44,586 - pydot.core - DEBUG - pydot core module initializing
2025-06-14 15:17:04,563 - livekit.agents - DEBUG - inference runner initialized
2025-06-14 15:17:04,563 - livekit.agents - DEBUG - inference runner initialized
2025-06-14 15:17:04,564 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:17:04,565 - livekit.agents - INFO - process initialized
2025-06-14 15:17:04,564 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:17:04,571 - livekit.agents - INFO - [1msee tracing information at http://localhost:53809/debug[0m
2025-06-14 15:17:04,728 - livekit.agents - INFO - registered worker
2025-06-14 15:17:04,775 - livekit.agents - INFO - received job request
2025-06-14 15:17:04,807 - livekit.agents - INFO - initializing job runner
2025-06-14 15:17:04,809 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:17:04,809 - livekit.agents - INFO - job runner initialized
2025-06-14 15:17:05,326 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-14 15:17:08,584 - debt_collection_agent - INFO - Agent session created successfully
2025-06-14 15:17:08,586 - livekit.agents - WARNING - Running <Task pending name='job_user_entrypoint' coro=<entrypoint() running at C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1\agent.py:179> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[_JobProc._run_job_task.<locals>.<lambda>() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:274, _JobProc._run_job_task.<locals>.log_exception() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:276]> took too long: 3.25 seconds
2025-06-14 15:17:08,588 - livekit.agents - WARNING - Running <Task pending name='job_user_entrypoint' coro=<entrypoint() running at C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1\agent.py:179> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[_JobProc._run_job_task.<locals>.<lambda>() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:274, _JobProc._run_job_task.<locals>.log_exception() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:276]> took too long: 3.25 seconds
2025-06-14 15:17:08,600 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-14 15:17:09,267 - livekit.agents - DEBUG - start reading stream
2025-06-14 15:17:18,316 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:17:18,871 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:17:29,459 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:17:29,849 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:17:29,914 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:17:31,613 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:19:23,954 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:19:23,961 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:19:23,967 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:19:28,693 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:19:28,698 - livekit.agents - INFO - starting worker
2025-06-14 15:19:28,698 - livekit.agents - INFO - starting inference executor
2025-06-14 15:19:28,751 - livekit.agents - INFO - initializing process
2025-06-14 15:19:33,175 - livekit.agents - DEBUG - initializing inference runner
2025-06-14 15:19:33,175 - livekit.agents - DEBUG - initializing inference runner
2025-06-14 15:19:35,176 - pydot - DEBUG - pydot initializing
2025-06-14 15:19:35,177 - pydot - DEBUG - pydot 3.0.4
2025-06-14 15:19:35,176 - pydot - DEBUG - pydot initializing
2025-06-14 15:19:35,177 - pydot - DEBUG - pydot 3.0.4
2025-06-14 15:19:35,223 - pydot.dot_parser - DEBUG - pydot dot_parser module initializing
2025-06-14 15:19:35,223 - pydot.dot_parser - DEBUG - pydot dot_parser module initializing
2025-06-14 15:19:35,226 - pydot.core - DEBUG - pydot core module initializing
2025-06-14 15:19:35,226 - pydot.core - DEBUG - pydot core module initializing
2025-06-14 15:19:43,146 - livekit.agents - DEBUG - inference runner initialized
2025-06-14 15:19:43,146 - livekit.agents - DEBUG - inference runner initialized
2025-06-14 15:19:43,147 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:19:43,147 - livekit.agents - INFO - process initialized
2025-06-14 15:19:43,147 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:19:43,153 - livekit.agents - INFO - [1msee tracing information at http://localhost:53865/debug[0m
2025-06-14 15:19:43,321 - livekit.agents - INFO - registered worker
2025-06-14 15:19:51,703 - livekit.agents - INFO - received job request
2025-06-14 15:19:51,735 - livekit.agents - INFO - initializing job runner
2025-06-14 15:19:51,737 - livekit.agents - INFO - job runner initialized
2025-06-14 15:19:51,738 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:19:53,459 - debt_collection_agent - INFO - Recording started with egress ID: EG_zmB28Beni4zt
2025-06-14 15:19:53,859 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-14 15:19:54,884 - debt_collection_agent - INFO - Agent session created successfully
2025-06-14 15:19:54,896 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-14 15:19:55,558 - livekit.agents - DEBUG - start reading stream
2025-06-14 15:20:04,782 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:20:06,477 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:20:16,749 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:20:17,409 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:20:17,417 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:20:17,927 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:20:35,955 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:20:35,963 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:20:36,694 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:20:40,213 - livekit.agents - DEBUG - stream closed
2025-06-14 15:20:40,214 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-14 15:20:40,231 - livekit.agents - DEBUG - session closed
2025-06-14 15:21:00,286 - livekit.agents - DEBUG - shutting down job task
2025-06-14 15:21:00,290 - livekit.agents - DEBUG - job exiting
2025-06-14 15:21:00,293 - livekit - WARNING - livekit::rtc_engine:450:livekit::rtc_engine - received session close: "signal client closed: \"stream closed\"" UnknownReason Resume
2025-06-14 15:21:00,296 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-14 15:24:07,072 - livekit.agents - INFO - shutting down worker
2025-06-14 15:24:07,075 - livekit.agents - INFO - process exiting
2025-06-14 15:29:29,299 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:29:29,306 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:29:29,311 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:29:34,021 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:29:34,025 - livekit.agents - INFO - starting worker
2025-06-14 15:29:34,030 - livekit.agents - INFO - [1msee tracing information at http://localhost:54047/debug[0m
2025-06-14 15:29:34,157 - livekit.agents - INFO - registered worker
2025-06-14 15:30:28,278 - livekit.agents - INFO - received job request
2025-06-14 15:30:28,315 - livekit.agents - INFO - initializing job runner
2025-06-14 15:30:28,316 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:30:28,317 - livekit.agents - INFO - job runner initialized
2025-06-14 15:30:30,000 - debt_collection_agent - INFO - Recording started with egress ID: EG_9STSnVJUdTPh
2025-06-14 15:30:30,324 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-14 15:30:31,217 - debt_collection_agent - INFO - Agent session created successfully
2025-06-14 15:30:31,223 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-14 15:30:32,048 - livekit.agents - DEBUG - start reading stream
2025-06-14 15:30:40,661 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:30:42,388 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:30:52,689 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:30:52,696 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:30:54,398 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:31:14,084 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:31:14,090 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:31:14,693 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:31:29,785 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:31:29,792 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:31:31,540 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:31:42,122 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:31:42,127 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:31:43,859 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:31:49,404 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-14 15:31:49,406 - livekit.agents - DEBUG - stream closed
2025-06-14 15:31:49,412 - livekit.agents - DEBUG - session closed
2025-06-14 15:32:13,115 - livekit.agents - DEBUG - shutting down job task
2025-06-14 15:32:13,118 - livekit.agents - DEBUG - job exiting
2025-06-14 15:32:13,125 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-14 15:33:10,638 - livekit.agents - INFO - shutting down worker
2025-06-14 15:38:50,607 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:38:50,616 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:38:50,624 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:38:56,130 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:38:56,137 - livekit.agents - INFO - starting worker
2025-06-14 15:38:56,142 - livekit.agents - INFO - [1msee tracing information at http://localhost:54173/debug[0m
2025-06-14 15:38:56,270 - livekit.agents - INFO - registered worker
2025-06-14 15:38:56,314 - livekit.agents - INFO - received job request
2025-06-14 15:38:56,343 - livekit.agents - INFO - initializing job runner
2025-06-14 15:38:56,346 - livekit.agents - INFO - job runner initialized
2025-06-14 15:38:56,346 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:38:58,194 - debt_collection_agent - INFO - Recording started with egress ID: EG_ufpZf6Lh5wRv
2025-06-14 15:38:58,641 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-14 15:38:59,652 - debt_collection_agent - INFO - Agent session created successfully
2025-06-14 15:38:59,660 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-14 15:39:00,185 - livekit.agents - DEBUG - start reading stream
2025-06-14 15:39:10,946 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:39:12,612 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:39:24,481 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:39:24,490 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:39:25,027 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:39:43,403 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:39:43,413 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:39:44,045 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:39:53,502 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-14 15:39:53,504 - livekit.agents - DEBUG - stream closed
2025-06-14 15:39:53,512 - livekit.agents - DEBUG - session closed
2025-06-14 15:39:56,198 - livekit.agents - INFO - shutting down worker
2025-06-14 15:39:56,201 - livekit.agents - DEBUG - shutting down job task
2025-06-14 15:39:56,202 - livekit.agents - DEBUG - job exiting
2025-06-14 15:39:56,264 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-14 15:44:42,439 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:44:42,445 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:44:42,450 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:44:47,480 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:44:47,486 - livekit.agents - INFO - starting worker
2025-06-14 15:44:47,489 - livekit.agents - INFO - [1msee tracing information at http://localhost:54291/debug[0m
2025-06-14 15:44:47,619 - livekit.agents - INFO - registered worker
2025-06-14 15:44:57,598 - livekit.agents - INFO - shutting down worker
2025-06-14 15:45:20,804 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:45:20,811 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:45:20,816 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:45:25,836 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:45:25,843 - livekit.agents - INFO - starting worker
2025-06-14 15:45:25,848 - livekit.agents - INFO - [1msee tracing information at http://localhost:54309/debug[0m
2025-06-14 15:45:26,044 - livekit.agents - INFO - registered worker
2025-06-14 15:45:26,087 - livekit.agents - INFO - received job request
2025-06-14 15:45:26,116 - livekit.agents - INFO - initializing job runner
2025-06-14 15:45:26,117 - livekit.agents - INFO - job runner initialized
2025-06-14 15:45:26,118 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:45:28,460 - debt_collection_agent - INFO - Recording started with egress ID: EG_8oJo3qBrAcaF
2025-06-14 15:45:28,801 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-14 15:45:29,773 - debt_collection_agent - INFO - Agent session created successfully
2025-06-14 15:45:29,780 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-14 15:45:30,426 - livekit.agents - DEBUG - start reading stream
2025-06-14 15:45:43,282 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:45:43,859 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:45:57,066 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:45:57,072 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:45:58,803 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:46:10,334 - livekit.agents - DEBUG - stream closed
2025-06-14 15:46:10,334 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-14 15:46:10,341 - livekit.agents - DEBUG - session closed
2025-06-14 15:46:17,456 - livekit.agents - INFO - shutting down worker
2025-06-14 15:46:17,460 - livekit.agents - DEBUG - shutting down job task
2025-06-14 15:46:17,462 - livekit.agents - DEBUG - job exiting
2025-06-14 15:46:17,497 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-14 15:46:27,073 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:46:27,080 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:46:27,085 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:46:31,679 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:46:31,684 - livekit.agents - INFO - starting worker
2025-06-14 15:46:31,688 - livekit.agents - INFO - [1msee tracing information at http://localhost:54363/debug[0m
2025-06-14 15:46:31,824 - livekit.agents - INFO - registered worker
2025-06-14 15:46:38,127 - livekit.agents - INFO - received job request
2025-06-14 15:46:38,159 - livekit.agents - INFO - initializing job runner
2025-06-14 15:46:38,160 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:46:38,160 - livekit.agents - INFO - job runner initialized
2025-06-14 15:46:39,887 - debt_collection_agent - INFO - Recording started with egress ID: EG_RoajQWWESSNK
2025-06-14 15:46:40,274 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-14 15:46:41,253 - debt_collection_agent - INFO - Agent session created successfully
2025-06-14 15:46:41,262 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-14 15:46:41,932 - livekit.agents - DEBUG - start reading stream
2025-06-14 15:46:49,739 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:46:50,339 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:47:03,870 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:47:03,876 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:47:04,415 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:47:09,979 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-14 15:47:09,981 - livekit.agents - DEBUG - stream closed
2025-06-14 15:47:09,992 - livekit.agents - WARNING - rotate_segment called while previous segment is still being rotated
2025-06-14 15:47:10,003 - livekit.agents - DEBUG - session closed
2025-06-14 15:47:11,334 - livekit.agents - INFO - shutting down worker
2025-06-14 15:47:11,336 - livekit.agents - DEBUG - shutting down job task
2025-06-14 15:47:11,339 - livekit.agents - DEBUG - job exiting
2025-06-14 15:47:11,380 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-14 15:48:00,193 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-14 15:48:00,199 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:48:00,208 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-14 15:48:05,416 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:48:05,421 - livekit.agents - INFO - starting worker
2025-06-14 15:48:05,425 - livekit.agents - INFO - [1msee tracing information at http://localhost:54411/debug[0m
2025-06-14 15:48:05,733 - livekit.agents - INFO - registered worker
2025-06-14 15:48:10,750 - livekit.agents - INFO - received job request
2025-06-14 15:48:10,779 - livekit.agents - INFO - initializing job runner
2025-06-14 15:48:10,780 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-14 15:48:10,781 - livekit.agents - INFO - job runner initialized
2025-06-14 15:48:12,346 - debt_collection_agent - INFO - Recording started with egress ID: EG_zAEr3QkJaEjg
2025-06-14 15:48:12,995 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-14 15:48:13,931 - debt_collection_agent - INFO - Agent session created successfully
2025-06-14 15:48:13,939 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-14 15:48:14,618 - livekit.agents - DEBUG - start reading stream
2025-06-14 15:48:27,148 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:48:27,820 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:48:38,004 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:48:38,022 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:48:39,786 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:48:51,115 - livekit.agents - DEBUG - received user transcript
2025-06-14 15:48:51,121 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-14 15:48:52,837 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-14 15:49:00,301 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-14 15:49:00,302 - livekit.agents - DEBUG - stream closed
2025-06-14 15:49:00,309 - livekit.agents - DEBUG - session closed
2025-06-14 15:49:22,981 - livekit - WARNING - livekit::rtc_engine:450:livekit::rtc_engine - received session close: "signal client closed: \"stream closed\"" UnknownReason Resume
2025-06-14 15:49:22,985 - livekit.agents - DEBUG - shutting down job task
2025-06-14 15:49:22,987 - livekit.agents - DEBUG - job exiting
2025-06-14 15:49:22,992 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-14 15:59:54,269 - livekit.agents - INFO - shutting down worker
2025-06-15 18:34:03,045 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-15 18:34:03,069 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 18:34:03,076 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-15 18:34:08,074 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 18:34:08,080 - livekit.agents - INFO - starting worker
2025-06-15 18:34:08,084 - livekit.agents - INFO - [1msee tracing information at http://localhost:50889/debug[0m
2025-06-15 18:34:08,212 - livekit.agents - INFO - registered worker
2025-06-15 18:34:13,721 - livekit.agents - INFO - received job request
2025-06-15 18:34:13,746 - livekit.agents - INFO - initializing job runner
2025-06-15 18:34:13,748 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 18:34:13,748 - livekit.agents - INFO - job runner initialized
2025-06-15 18:34:15,446 - debt_collection_agent - INFO - Recording started with egress ID: EG_caCE4McpJwUX
2025-06-15 18:34:15,788 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-15 18:34:18,835 - debt_collection_agent - INFO - Agent session created successfully
2025-06-15 18:34:18,837 - livekit.agents - WARNING - Running <Task pending name='job_user_entrypoint' coro=<entrypoint() running at C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1\agent.py:202> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[_JobProc._run_job_task.<locals>.<lambda>() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:274, _JobProc._run_job_task.<locals>.log_exception() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:276]> took too long: 3.05 seconds
2025-06-15 18:34:18,838 - livekit.agents - WARNING - Running <Task pending name='job_user_entrypoint' coro=<entrypoint() running at C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1\agent.py:202> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[_JobProc._run_job_task.<locals>.<lambda>() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:274, _JobProc._run_job_task.<locals>.log_exception() at C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\job_proc_lazy_main.py:276]> took too long: 3.05 seconds
2025-06-15 18:34:18,845 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-15 18:34:19,529 - livekit.agents - DEBUG - start reading stream
2025-06-15 18:34:30,489 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 18:34:32,187 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 18:34:42,982 - livekit.agents - DEBUG - received user transcript
2025-06-15 18:34:42,989 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 18:34:44,676 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 18:34:51,882 - livekit.agents - DEBUG - received user transcript
2025-06-15 18:34:52,945 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 18:34:53,523 - livekit.agents - DEBUG - received user transcript
2025-06-15 18:34:53,529 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 18:34:55,223 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 18:35:04,062 - livekit.agents - DEBUG - received user transcript
2025-06-15 18:35:04,071 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 18:35:05,704 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 18:35:14,046 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-15 18:35:14,048 - livekit.agents - DEBUG - stream closed
2025-06-15 18:35:14,057 - livekit.agents - DEBUG - session closed
2025-06-15 18:35:37,889 - livekit - WARNING - livekit::rtc_engine:450:livekit::rtc_engine - received session close: "signal client closed: \"stream closed\"" UnknownReason Resume
2025-06-15 18:35:37,890 - livekit.agents - DEBUG - shutting down job task
2025-06-15 18:35:37,893 - livekit.agents - DEBUG - job exiting
2025-06-15 18:35:37,901 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-15 18:41:19,398 - livekit.agents - INFO - shutting down worker
2025-06-15 18:44:09,096 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-15 18:44:09,103 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 18:44:09,108 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-15 18:44:13,558 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 18:44:13,563 - livekit.agents - INFO - starting worker
2025-06-15 18:44:13,568 - livekit.agents - INFO - [1msee tracing information at http://localhost:51109/debug[0m
2025-06-15 18:44:13,681 - livekit.agents - INFO - registered worker
2025-06-15 18:56:20,369 - livekit.agents - INFO - shutting down worker
2025-06-15 19:20:14,588 - debt_collection_agent - INFO - Starting debt collection telephony agent...
2025-06-15 19:20:14,596 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 19:20:14,601 - livekit.agents - DEV - Watching C:\Users\mamle\visualstudiocode\Riverline\Riverline-Hiring-Assignement\challenge-1
2025-06-15 19:20:19,278 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 19:20:19,284 - livekit.agents - INFO - starting worker
2025-06-15 19:20:19,290 - livekit.agents - INFO - [1msee tracing information at http://localhost:51686/debug[0m
2025-06-15 19:20:19,412 - livekit.agents - INFO - registered worker
2025-06-15 19:20:39,597 - livekit.agents - INFO - received job request
2025-06-15 19:20:39,622 - livekit.agents - INFO - initializing job runner
2025-06-15 19:20:39,624 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 19:20:39,624 - livekit.agents - INFO - job runner initialized
2025-06-15 19:20:41,251 - debt_collection_agent - INFO - Recording started with egress ID: EG_HBQcaVdchXpL
2025-06-15 19:20:41,669 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-15 19:20:42,864 - debt_collection_agent - INFO - Agent session created successfully
2025-06-15 19:20:42,876 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-15 19:20:43,656 - livekit.agents - DEBUG - start reading stream
2025-06-15 19:20:57,366 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:20:59,080 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:21:10,378 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:21:10,389 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:21:12,061 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:21:27,033 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:21:27,117 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:21:28,754 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:21:40,871 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:21:41,773 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:21:41,807 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:21:43,578 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:21:58,877 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:21:58,897 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:21:59,438 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:22:04,767 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-15 19:22:04,769 - livekit.agents - DEBUG - stream closed
2025-06-15 19:22:04,777 - livekit.agents - DEBUG - session closed
2025-06-15 19:22:24,894 - livekit.agents - DEBUG - shutting down job task
2025-06-15 19:22:24,897 - livekit.agents - DEBUG - job exiting
2025-06-15 19:22:24,900 - livekit - WARNING - livekit::rtc_engine:450:livekit::rtc_engine - received session close: "signal client closed: \"stream closed\"" UnknownReason Resume
2025-06-15 19:22:24,907 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-15 19:23:10,303 - livekit.agents - INFO - received job request
2025-06-15 19:23:10,330 - livekit.agents - INFO - initializing job runner
2025-06-15 19:23:10,331 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 19:23:10,332 - livekit.agents - INFO - job runner initialized
2025-06-15 19:23:12,014 - debt_collection_agent - INFO - Recording started with egress ID: EG_Pbejgt3idXYy
2025-06-15 19:23:12,323 - debt_collection_agent - INFO - Creating agent session with configured models
2025-06-15 19:23:12,909 - debt_collection_agent - INFO - Agent session created successfully
2025-06-15 19:23:12,915 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2025-06-15 19:23:13,573 - livekit.agents - DEBUG - start reading stream
2025-06-15 19:23:23,245 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:23:24,985 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:23:35,768 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:23:35,776 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:23:37,482 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:23:47,065 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:23:47,812 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:23:47,829 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:23:48,635 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:23:48,658 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:23:49,244 - google_genai.models - INFO - AFC remote call 1 is done.
2025-06-15 19:23:57,294 - livekit.agents - DEBUG - received user transcript
2025-06-15 19:23:57,301 - google_genai.models - INFO - AFC is enabled with max remote calls: 10.
2025-06-15 19:23:57,580 - livekit.agents - DEBUG - stream closed
2025-06-15 19:23:57,582 - livekit.agents - DEBUG - closing agent session due to participant disconnect
2025-06-15 19:23:57,596 - livekit.agents - DEBUG - session closed
2025-06-15 19:24:19,897 - livekit.agents - DEBUG - shutting down job task
2025-06-15 19:24:19,900 - livekit.agents - DEBUG - job exiting
2025-06-15 19:24:19,905 - livekit - WARNING - livekit::rtc_engine:450:livekit::rtc_engine - received session close: "signal client closed: \"stream closed\"" UnknownReason Resume
2025-06-15 19:24:19,912 - livekit.agents - DEBUG - http_session(): closing the httpclient ctx
2025-06-15 21:22:13,337 - livekit.agents - WARNING - failed to connect to livekit, retrying in 0s
Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\worker.py", line 693, in _connection_task
    await self._run_ws(ws)
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\worker.py", line 774, in _run_ws
    await asyncio.gather(*tasks)
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\worker.py", line 737, in _recv_task
    msg = await ws.receive()
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\client_ws.py", line 378, in receive
    await self.pong(msg.data)
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\client_ws.py", line 234, in pong
    await self._writer.send_frame(message, WSMsgType.PONG)
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\_websocket\writer.py", line 125, in send_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport
2025-06-15 21:22:13,745 - livekit.agents - WARNING - failed to connect to livekit, retrying in 2s
Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1357, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 995, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1026, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\resolver.py", line 39, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 868, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\worker.py", line 654, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\client.py", line 1004, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1363, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host riverline-ij23yty9.livekit.cloud:443 ssl:default [getaddrinfo failed]
2025-06-15 21:22:15,791 - livekit.agents - WARNING - failed to connect to livekit, retrying in 4s
Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1357, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 995, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1026, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\resolver.py", line 39, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 868, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\worker.py", line 654, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\client.py", line 1004, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiohttp\connector.py", line 1363, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host riverline-ij23yty9.livekit.cloud:443 ssl:default [getaddrinfo failed]
2025-06-15 21:22:19,956 - livekit.agents - INFO - registered worker
2025-06-15 21:56:10,611 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 21:56:10,618 - livekit.agents - INFO - starting worker
2025-06-15 21:56:10,624 - livekit.agents - INFO - [1msee tracing information at http://localhost:54027/debug[0m
2025-06-15 21:56:10,753 - livekit.agents - INFO - registered worker
2025-06-15 21:56:10,625 - livekit.agents - ERROR - Error in _read_ipc_task
Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 35, in recv_bytes
    len_bytes = await self._reader.readexactly(4)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 748, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\utils\log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\cli\watcher.py", line 120, in _read_ipc_task
    msg = await channel.arecv_message(self._pch, proto.IPC_MESSAGES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\ipc\channel.py", line 47, in arecv_message
    return _read_message(await dplx.recv_bytes(), messages)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\livekit\agents\utils\aio\duplex_unix.py", line 43, in recv_bytes
    raise DuplexClosed() from e
livekit.agents.utils.aio.duplex_unix.DuplexClosed
2025-06-15 21:56:24,182 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 21:56:24,186 - livekit.agents - INFO - starting worker
2025-06-15 21:56:24,191 - livekit.agents - INFO - [1msee tracing information at http://localhost:54035/debug[0m
2025-06-15 21:56:24,324 - livekit.agents - INFO - registered worker
2025-06-15 21:56:34,435 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 21:56:34,440 - livekit.agents - INFO - starting worker
2025-06-15 21:56:34,444 - livekit.agents - INFO - [1msee tracing information at http://localhost:54043/debug[0m
2025-06-15 21:56:34,605 - livekit.agents - INFO - registered worker
2025-06-15 22:00:45,995 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 22:00:46,001 - livekit.agents - INFO - starting worker
2025-06-15 22:00:46,006 - livekit.agents - INFO - [1msee tracing information at http://localhost:54113/debug[0m
2025-06-15 22:00:46,141 - livekit.agents - INFO - registered worker
2025-06-15 22:02:18,690 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 22:02:18,695 - livekit.agents - INFO - starting worker
2025-06-15 22:02:18,700 - livekit.agents - INFO - [1msee tracing information at http://localhost:54154/debug[0m
2025-06-15 22:02:18,836 - livekit.agents - INFO - registered worker
2025-06-15 22:02:30,063 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 22:02:30,068 - livekit.agents - INFO - starting worker
2025-06-15 22:02:30,072 - livekit.agents - INFO - [1msee tracing information at http://localhost:54162/debug[0m
2025-06-15 22:02:30,205 - livekit.agents - INFO - registered worker
2025-06-15 22:03:01,160 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 22:03:01,167 - livekit.agents - INFO - starting worker
2025-06-15 22:03:01,172 - livekit.agents - INFO - [1msee tracing information at http://localhost:54178/debug[0m
2025-06-15 22:03:01,308 - livekit.agents - INFO - registered worker
2025-06-15 22:03:19,944 - asyncio - DEBUG - Using proactor: IocpProactor
2025-06-15 22:03:19,950 - livekit.agents - INFO - starting worker
2025-06-15 22:03:19,956 - livekit.agents - INFO - [1msee tracing information at http://localhost:54191/debug[0m
2025-06-15 22:03:20,084 - livekit.agents - INFO - registered worker
